# Generated by Django 6.0.4 on 2026-04-21 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('project_code', models.CharField(max_length=50, unique=True)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('station_name', models.CharField(default='TS-08', max_length=80)),
                ('is_connected', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('report_type', models.CharField(choices=[('daily', 'Daily Survey Summary'), ('dtm', 'DTM Surface Report'), ('volume', 'Area & Volume Report'), ('profile', 'Elevation Profile')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_ready', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.project')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SurveyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('northing', models.DecimalField(decimal_places=3, max_digits=12)),
                ('easting', models.DecimalField(decimal_places=3, max_digits=12)),
                ('elevation', models.DecimalField(decimal_places=3, max_digits=10)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_points', to='core.project')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
